export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    // CART_CLEAR_START: 'CART_CLEAR_START',
    // CART_CLEAR_SUCCESS: 'CART_CLEAR_SUCCESS',
    // CART_CLEAR_FAILURE: 'CART_CLEAR_FAILURE'
    CART_CLEAR: 'CART_CLEAR'
};